spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
  import:
    - classpath:sub-config/application-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
