spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    version: 1
#cloud:
#  aws:
#    region:
#      static: ap-northeast-2
#    s3:
#      bucket: k-bnt-15-files
#    credentials:
#      access-key: ${S3-ACCESS-KEY}
#      secret-key: ${S3-SECRET-KEY}
#    stack:
#      auto: false

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate.sql: debug
---

spring:
  config:
    activate:
      on-profile: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${RDS-URL}
#    username: ${RDS-USERNAME}
#    password: ${RDS-PASSWORD}

logging:
  level:
    org:
      hibernate.sql: info
