spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: local
    import: application.yml
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate.sql: debug
---

spring:
  config:
    activate:
      on-profile: prod
  import:
    - classpath:dockertest-privates/application-prod.yml