name: spring server ci cd

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTIONTOKEN }}

      - name: update submodules
        run: git submodule update --remote

      - name: 자바 11 설정
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 빌드
        run: ./gradlew build

      - name: 도커 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_IMG }} .

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_IMG }}

      - name: 배포하기
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            sudo chmod 777 ./deploy.sh
            ./deploy.sh
            docker image prune -f
            
